src/Entity/Questions.php
<?php

namespace App\Entity;

use App\Repository\QuestionsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuestionsRepository::class)
 */
class Questions
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $textQuestion;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_multiple;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTextQuestion(): ?string
    {
        return $this->textQuestion;
    }

    public function setTextQuestion(string $textQuestion): self
    {
        $this->textQuestion = $textQuestion;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getIsMultiple(): ?bool
    {
        return $this->is_multiple;
    }

    public function setIsMultiple(bool $is_multiple): self
    {
        $this->is_multiple = $is_multiple;

        return $this;
    }
    public function __toString() {
        return $this->id;
    }
}

src/Form/QuestionsType.php
<?php

namespace App\Form;

use App\Entity\Questions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuestionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('textQuestion')
            ->add('is_multiple')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Questions::class,
        ]);
    }
}

src/Controller/QuestionsController.php
<?php

namespace App\Controller;

use App\Entity\Reponses;
use App\Form\ReponsesType;
use App\Entity\Questions;
use App\Entity\Resultats;
use App\Form\QuestionsType;
use App\Repository\QuestionsRepository;
use App\Repository\ReponsesRepository;
use App\Repository\ResultatsRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/questions')]
class QuestionsController extends AbstractController
{
    #[Route('/', name: 'questions_index', methods: ['GET'])]
    public function index(QuestionsRepository $questionsRepository): Response
    {
        return $this->render('questions/index.html.twig', [
            'questions' => $questionsRepository->findAll(),
        ]);

    }

    #[Route('/new', name: 'questions_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserRepository $userRepository): Response
    {
        $question = new Questions();
        $form = $this->createForm(QuestionsType::class, $question);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $question->setUser($userRepository->find(2));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($question);
            $entityManager->flush();

            return $this->redirectToRoute('questions_index');
        }

        return $this->render('questions/new.html.twig', [
            'question' => $question,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/show/{id}', name: 'questions_show', methods: ['GET'])]
    public function show(Questions $question, ReponsesRepository $reponsesRepository): Response
    {
        $reponses = $reponsesRepository->findBy(['questions' => $question->getId()]);
        return $this->render('questions/show.html.twig', [
            'question' => $question,
            'reponses' => $reponses
        ]);
    }

    #[Route('/edit/{id}', name: 'questions_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Questions $question): Response
    {
        $form = $this->createForm(QuestionsType::class, $question);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('questions_index');
        }

        return $this->render('questions/edit.html.twig', [
            'question' => $question,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'questions_delete', methods: ['POST'])]
    public function delete(Request $request, Questions $question): Response
    {
        if ($this->isCsrfTokenValid('delete'.$question->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($question);
            $entityManager->flush();
        }

        return $this->redirectToRoute('questions_index');
    }

    #[Route('/show/{id}', name: 'questions_answer', methods: ['GET', 'POST'])]
    public function answer(Request $request, Questions $questions, ReponsesRepository $reponses, ResultatsRepository $resultats): Response
    {

        if ($resultats->haveAlreadyAnswered($questions->getId(), $request->getClientIp())) {
            $this->addFlash('error', 'vous avez déjà répondu à ce sondage');
            return $this->redirectToRoute('questions_index', ['id' => $questions->getId()]);
        }
        else if($request->getMethod() === 'POST'){
            $results = $request->request->get('answer');
            $entityManager = $this->getDoctrine()->getManager();
            foreach($results as $result){
                $answer = new Resultats();
                $answer->setUser($this->getUser());
                $answer->setUserIp($request->getClientIp());
                $answer->setReponse($reponses->find($result));
                $entityManager->persist($answer);
                $entityManager->flush();
            }
            $this->addFlash('success', 'Réponses ajouté avec succès');
            return $this->redirectToRoute('questions_index');
        }
    }
    
    #[Route('/results/{id}', name: 'questions_results', methods: ['GET'])]
    public function results(Questions $question,  ReponsesRepository $reponsesRepository, ResultatsRepository $resultatsRepository): Response
    {
        $reponses = $reponsesRepository->findBy(['questions' => $question->getId()]);
        $resultats = [];
        $resultsTotal = 0;

        foreach ($reponses as $key) {
            $resultats[$key->getId()] = count($resultatsRepository->findBy(['reponse' => $key->getId()]));
        }

        foreach($resultats as $keyy){
            $resultsTotal += $keyy;
        }
        
        
        return $this->render('questions/results.html.twig', [
            'question' => $question,
            'reponses' => $reponses,
            'resultats' => $resultats,
            'resultsTotal' => $resultsTotal
        ]);
    }


}

templates/questions/_delete_form.html.twig
<form method="post" action="{{ path('questions_delete', {'id': question.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ question.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/questions/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Questions{% endblock %}

{% block body %}
 <main style="padding: 2%;">
    <h1>Editer la Question</h1>

    

    {{ include('questions/_form.html.twig', {'button_label': 'Update'}) }}


    {{ include('questions/_delete_form.html.twig') }}

    <a href="{{ path('questions_index') }}">Retour à la liste</a>
    </main>
{% endblock %}

templates/questions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Questions index{% endblock %}

{% block body %}
 <main style="padding: 2%;">
    <h1>Questions index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Question</th>
                <th>Multipe réponse</th>
                <th> Résultat </th>
                <th> Répondre au sondage</th>
                <th> Modifier réponses </th>
                <th> Modifier </th>
            </tr>
        </thead>
        <tbody>
        {% for question in questions %}
            <tr>
                <td>{{ question.id }}</td>
                <td>{{ question.textQuestion }}</td>
                <td>{{ question.isMultiple ? '<i class="fas fa-fw fa-check"></i>' : '<i class="fas fa-fw fa-times"></i>' }}</td>
                <td>
                    <a href="{{ path('questions_results', {'id': question.id}) }}"> <i class="fas fa-fw fa-poll-h"></i> Résultats </a>
                </td>
                <td>
                    <a href="{{ path('questions_show', {'id': question.id}) }}"> <i class="fas fa-fw fa-reply"></i> répondre</a>
                </td>
                <td>
                    <a href="{{ path('reponses_index', {'id': question.id}) }}"> <i class="fas fa-fw fa-plus-square"></i> éditer réponses</a>
                </td>
                <td>
                    <a href="{{ path('questions_edit', {'id': question.id}) }}"> <i class="fas fa-fw fa-edit"></i> éditer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucune questions trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div style="margin-left: 4%; margin-bottom: 2%;">
        <a href="{{ path('questions_new') }}">Créer une nouvelle question</a>
    </div>

</main>

{% endblock %}

templates/questions/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Questions{% endblock %}

{% block body %}
    <h1>Créer une nouvelle question</h1>

    {{ include('questions/_form.html.twig') }}

    <a href="{{ path('questions_index') }}">Retour à la liste</a>
{% endblock %}

templates/questions/results.html.twig
{% extends 'base.html.twig' %}

{% block title %} Résultats : {{ question.textQuestion }} {% endblock %}

{% block body %}
    <main style="padding: 2%;">
    <h1> Résultat de la question : {{ question.textQuestion }} </h1>

    <div style="margin-left: 2%; font-size: 20px">
        {% for reponse in reponses %}
            <p> {{reponse.textReponse}} = {{ resultats[reponse.id] }} vote(s)</p>
        {% endfor %}
    </div>

    <p> Nombre total de votes : {{ resultsTotal }} </p>

    <a href="{{ path('questions_index') }}"> <p style="margin-top: 2%; margin-left: 2%;"> Retour à la liste </p> </a>

    </main>
{% endblock %}

templates/questions/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} Question : {{ question.textQuestion }} {% endblock %}

{% block body %}
 <main style="padding: 2%;">
    <h1> {{ question.textQuestion }} </h1>

    <form action="{{ path('questions_answer', {'id': question.id}) }}" method="post" style="margin-left: 2%;">
        {% set input_type=question.isMultiple ? 'checkbox' : 'radio' %}

        {% for reponse in reponses %}
            <input type="{{input_type}}" name="answer[]" value="{{reponse.id}}"> {{reponse.textReponse}} <br />
        {% endfor %}

        <button style="margin-top: 1%;"> Envoyer </button>
    </form>

    <a href="{{ path('questions_index') }}"> <p style="margin-top: 2%; margin-left: 2%;"> Retour à la liste </p> </a>
</main>
{% endblock %}